
name: API_AI workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.3
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          # Выбор версии Python
          python-version: 3.9
      - name: Install dependencies
        run: |
          # обновление pip
          python -m pip install --upgrade pip 
          # установка flake8 и его плагинов
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          # установка зависимостей
          pip install -r app/requirements.txt
      - name: Test with flake8 and django tests
        run: |
          # запуск проверки проекта по flake8
          python -m flake8
